services:
  app:
    image: ramageek/image:php8.3-laravel
    ports:
     - '${APP_PORT:-8080}:8080'
    volumes:
      - '.:/var/www/html'
    networks:
      - proxy
  redis:
    image: redis:alpine
    volumes:
      - ./storage/infra/redis:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 3
networks:
  proxy:
    driver: bridge
    external: true
